name: pre-commit
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
runs:
  using: composite
  steps:
  - run: python -m pip install 'pre-commit>=4.1.0'
    shell: bash
  - run: python -m pip freeze --local
    shell: bash
  - uses: actions/cache@v4
    with:
      path: |
        ~/.cache/pre-commit
        ~/.cache/R/renv
      key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
  - run: SKIP=runic pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
    shell: bash
