#syntax=docker/dockerfile:1-labs

# Use Julia official image as base
FROM julia:1.11.7

ARG GIT_COMMIT_SHA
ENV GIT_COMMIT_SHA=$GIT_COMMIT_SHA

ARG GIT_BRANCH_NAME
ENV GIT_BRANCH_NAME=$GIT_BRANCH_NAME

# Install and precompile dependencies
COPY /EpiAutoGP /EpiAutoGP

WORKDIR /EpiAutoGP

RUN julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate()'

# Threads Overloadable by user at runtime
ENV JULIA_NUM_THREADS=auto

# Default command to run the model
ENTRYPOINT ["julia", "--project", "run.jl"]
